### ISSUE TITLE
4 roles limit

### ISSUE THREAD

**Issue by thiagochristof** [supreen/form2role-bot#2]
Hello, the 4 roles limit would be a discord limit or it's possible to change the code eg. to a limit of 10 roles? tks

**Comment by supreen** [comment]
No. It is not discord limit. and it is possible to extend it through changing the code. 
It was set to 4 to save the resources and because of the "case use" at that time.

**Comment by supreen** [comment]
you will need to understand the code and go deep into it to change the number of the roles. i hope that answer you question and i am closing this issue. Please get to me whenever you need any assistance. best of luck.
